<a href="https://colab.research.google.com/github/brayannmb/projeto_previsao_vendas/blob/main/projeto_house_prices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Projeto de Estudo - Data Science**

------------------------------------------------------------

Para o meu segundo projeto de estudos em Aprendizado de Máquina, escolhi outra [competição](https://www.kaggle.com/c/house-prices-advanced-regression-techniques/overview) muito famosa no mundo de Data Science, a análise de preços de vandas de casas em Ames, Iowa.

##**Previsão de Vendas de Casas**

<center><img width="80%" src="https://github.com/brayannmb/projeto_previsao_vendas/blob/main/banner%20houses.jpg?raw=true"></center>

##**Introdução - Business Understanding**

Segundo a [BBC News](https://www.bbc.com/portuguese/geral-58025702), em diversos países do mundo os valores das casas estão em alta por conta da pandemia. 

**Mas o que um projeto de aprendizado de máquina poderia colaborar com o setor imobiliário?**

Imagine que você é um Cientista de Dados e trabalha para uma grande empresa do setor. Então, o chefe do departamento de Teconlogia pediu para que você e os desenvolvedores  trabalhem juntos no desenvolvimento de um novo projeto.
 
Este projeto tem por objetivo calcular o valor do preço de imóveis com base nas informações que o usuário inseriu, como quantidade quartos, suítes, tamanho em m2, etc. 

Diante deste cenário, onde os preços dos imóveis estão em alta, é necessário que esta nova *feature* calcule os preços com o máximo de assertividade possível, para que os usuários não se decepcionem ao estimar um imóvel de um dormitório, 30 m2, interior de SP e o valor sair mais de 800 mil reais.  

Portanto, este será o cenário para a elaboração deste projeto, analisar e buscar predizer valores para casas com base nos preços históricos e nas caracteristicas de cada imóvel.

##**Métrica de Avaliação**

A métrica para avaliar o modelo de *machine learning* será a [RMSE](https://en.wikipedia.org/wiki/Root-mean-square_deviation) (root-mean-square error) - erro médio quadrático.

##**1.Obtenção dos Dados**

A primeira etapa deste projeto será obter os conjuntos de dados que serão utilizados. Os dados podem ser extraidos deste [link](https://www.kaggle.com/c/house-prices-advanced-regression-techniques/data) pelo site do Kaggle.

Os dados estão dividos entre dois conjuntos, eles são:

* **train.csv** - Conjunto de dados para realzar análise exploratória e treinar o modelo de *machine learning*.
* **test.csv** - Conjunto de dados para testar o desempenho do modelo, aplicando dados ainda não vistos pelo mesmo. 

**Libraries que serão utilizadas:**

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#importando conjunto de dados

train = pd.read_csv('https://raw.githubusercontent.com/brayannmb/projeto_previsao_vendas/main/train.csv')

##**Compreensão dos Dados**

Nesta etapa, irei analisar a fundo sobre os dados e buscar uma melhor compreensão sobre eles.

###**Análise Exploratória de Dados**

Umas etapas que consomem mais tempo de um Cientista de Dados é análise descritiva e a estruturação dos dados, quase **80%** do tempo é destinado para essas etapas.

Para uma primeira visualização sobre os dados, irei analisar as primeiras e últimas entradas.

In [3]:
#5 primeiras entradas

train.head()

   Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0   1          60       RL  ...        WD         Normal    208500
1   2          20       RL  ...        WD         Normal    181500
2   3          60       RL  ...        WD         Normal    223500
3   4          70       RL  ...        WD        Abnorml    140000
4   5          60       RL  ...        WD         Normal    250000

[5 rows x 81 columns]

In [4]:
#5 últimas entradas

train.tail()

        Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
1455  1456          60       RL  ...        WD         Normal    175000
1456  1457          20       RL  ...        WD         Normal    210000
1457  1458          70       RL  ...        WD         Normal    266500
1458  1459          20       RL  ...        WD         Normal    142125
1459  1460          20       RL  ...        WD         Normal    147500

[5 rows x 81 columns]

Apenas visualizando as entradas acima, é possível identificar variáveis como `Alley`, `PoolQC`, `Fence` e `MiscFeature` com valores ausentes. Embora, ainda é cedo para fazer qualquer conclusão. 

Antes de analisar as variáveis que possuem valores ausentes, irei incluir um dicionário de variáveis, para que facilite o entendimento da análise.

In [5]:
#quantidade de colunas: 

print(f'Quantidade de colunas: {train.shape[1]}')

Quantidade de colunas: 81

###**Dicionário de Variáveis:**

O dicionário de variáveis é uma ótima ferramenta para obter um melhor entendimento sobre as *features* de um conjunto de dados.
Como foi apresentado acima, o conjunto de dados de treino possui 81 colunas, elas são: 

**Variáveis qualitativas (nominal):** 
* MSZoning: Classificação geral de zoneamento
* Street: Tipo de estrada
* Alley: Tipo de caminho de acesso para a propriedade
* LotConfig: Tipo do lote 
* Neighborhood: Bairros próximos
* Condition1: Proximidade da estrada princípal
* Condition2: Proximidade da estrada princípal (se houver uma segunda)
* BldgType: Tipo de habitação
* RoofStyle: Tipo de cobertura (telhado)
* RoofMatl: Material da cobertura (telhado)
* Exterior1st: Material da cobertura externa da casa
* Exterior2nd: Material da cobertura externa da casa (se houver um segundo material)
* MasVnrType: Tipo de folheado de alvenaria
* Foundation: Tipo de fundação 
* Heating: Tipo de sistema de aquecimento
* CentralAir: Ar condicionado
* Electrical: Tipo de sistema elétrico
* GarageType: Localização da garagem
* GarageFinish: Parte interior da garagem finalizada
* PavedDrive: Caminho pavimentado
* MiscFeature: Recursos diversos não incluídos em outras categorias
* SaleType: Tipo de venda
* SaleCondition: Condição de venda

**Variáveis qualitativas (ordinal):**

* LandContour: Nivelamento da propriedade
* LotShape: Classificação do tamanho da propriedade
* LandSlope: Inclinação do imóvel
* Utilities: Utilidades do imóvel 
* HouseStyle: Estilo de habitação
* OverallQual: Avalia material geral e acabamento da casa
* OverallCond: Avalia condições gerais da casa
* ExterQual: Qualidade do material da área externa
* ExterCond: Presente condição do material área externa
* BsmtQual: Qualidade do porão
* BsmtCond: Condições gerais do porão
* BsmtExposure: Exposição do porão
* BsmtFinType1: Classificação da área acabada do porão
* BsmtFinType2: Classificação da área acabada do porão (se houver a segunda)
* HeatingQC: Qualidade e condições do sistema de aquecimento
* KitchenQual: Qualidade da cozinha
* Functional: Avaliação da funcionalidade doméstica
* FireplaceQu: Qualidade da lareira
* GarageQual: Qualidade da garagem
* GarageCond: Condições da garagem
* PoolQC: Qualidade da piscina
* Fence: Qualidade da cerca

**Variáveis quantitativas:**

* SalePrice - Preço das casas (Variável target) 
* MSSubClass: Tipo de propriedade envolvida na venda
* LotFrontage: Pés lineares de rua conectados à propriedade
* LotArea: Tamanho do lote em pés quadrados
* YearBuilt: Ano de construção
* YearRemodAdd: Data de reforma (a mesma de construção se o imóvel não possuir reformas)
* MasVnrArea: Área de folheado de alvenaria em pés quadrados
* BsmtFinSF1: Tipo 1 em pés quadrados
* BsmtFinSF2: Tipo 2 em pés quadrados
* BsmtUnfSF: Pés quadrados inacabados de área do porão
* TotalBsmtSF: Total de pés quadrados de área do porão
* 1stFlrSF: Primeiro andar em pés quadrados
* 2ndFlrSF: Segundo andar em pés quadrados
* LowQualFinSF: Baixo acabamento em todos os andares
* GrLivArea: Área de estar acima do nível (solo) em pés quadrados
* BsmtFullBath: Banheiros
* BsmtHalfBath: Lavabos do porão
* FullBath: Banheiros completos acima do nível do solo
* HalfBath: Lavabos acima do nível do solo
* Bedroom: Número de quartos
* Kitchen: Number of kitchens
* TotRmsAbvGrd: Total de quartos (não inclui banheiros)
* Fireplaces: Número de lareiras
* GarageYrBlt: Ano de construção da garagem
* GarageCars: Tamanho da garagem em capacidade de carros
* GarageArea: Tamanho da garage em pés quadrados
* WoodDeckSF: Área do deck de madeira em pés quadrados
* OpenPorchSF: Área de varanda aberta em pés quadrados
* EnclosedPorch: Área de varanda fechada em pés quadrados
* 3SsnPorch: Área da varanda de três temporadas em pés quadrados (!)
* ScreenPorch: Área da tela da varanda em pés quadrados (!)
* PoolArea: Aréa da piscina em pés quadrados
* MiscVal: Valor dos recursos não incluídos
* MoSold: Mês de venda
* YrSold: Ano de venda


Em algumas das traduções estão descritas "pés quadrados", essa é uma medida utilizada para medir área nos Estados Unidos e Reino Unido. Um [pé quadrado](https://pt.wikipedia.org/wiki/P%C3%A9_quadrado) equivale a 0,09290304 metros quadrados.

Após compreender melhor sobre o significado de cada variável, está na hora de descobrir os tipos primitivos de cada uma.

In [6]:
#informações sobre as variáveis

train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1452 non-null   object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

Um dos pontos que devemos tomar muito cuidado quando estamos analisando os tipos de varáveis é quando temos variáveis qualitativas e que estão representadas por valores númericos, como as variáveis: `MSSubClass`, `OverallQual` e `OverallCond`.

Mesmo que essas variáveis possuam valores númericos, elas não podem ser classificadas como quantitativas e também não se deve aplicar operações matemáticas e estatísticas descritivas, apenas a moda.

Analisando o resultado acima, também foi possível descobrir variáveis que possuem uma grande quantidade valores ausentes, como por exemplo as variáveis `Alley`, `PoolQC`, `Fence` e `MiscFeature`.

Pensando nisso, os próximos passos da análise serão entender um pouco mais sobre estes valores ausentes.

In [14]:
((train.isnull().sum() / train.shape[0]) * 100).sort_values(ascending=False)[:20]

PoolQC          99.520548
MiscFeature     96.301370
Alley           93.767123
Fence           80.753425
FireplaceQu     47.260274
LotFrontage     17.739726
GarageCond       5.547945
GarageType       5.547945
GarageYrBlt      5.547945
GarageFinish     5.547945
GarageQual       5.547945
BsmtExposure     2.602740
BsmtFinType2     2.602740
BsmtFinType1     2.534247
BsmtCond         2.534247
BsmtQual         2.534247
MasVnrArea       0.547945
MasVnrType       0.547945
Electrical       0.068493
Utilities        0.000000
dtype: float64

De acordo com o resultado acima, podemos ver o percentual de valores ausentes de cada variável. 

Mesmo que exista muitos valores faltantes, é necessário buscar coompreender melhor esses dados. Dessa maneira, como por exemplo podemos ver a que variável `PoolQC` referente a qualidade da piscina possui quase 100% de seus valores ausentes. No entanto, a variável `PoolArea` que está relacionada ao tamanho da piscina não possui nenhum valor ausente.

**Por que isso aconteceu?**

In [15]:
train.PoolArea.value_counts()

0      1453
738       1
648       1
576       1
555       1
519       1
512       1
480       1
Name: PoolArea, dtype: int64

In [21]:
train.loc[train.PoolArea > 0][['PoolArea', 'PoolQC']]

      PoolArea PoolQC
197        512     Ex
810        648     Fa
1170       576     Gd
1182       555     Ex
1298       480     Gd
1386       519     Fa
1423       738     Gd

Com o resultado acima, entedemos que o valor 0 está atrelado à uma moradia que não possui piscina na variável `PoolArea` e apenas as 7 residências que possuem piscinas terão valores na variável `PoolQC`. Então, a ausência de valores muitas vezes pode ter um outro significado.